# KONVERSI DATETIME

In [15]:
import pandas as pd
import os

pd.set_option("display.max_columns", None)

In [8]:
DATA_PATH = "../data/raw/station_hour.csv"
df = pd.read_csv(DATA_PATH)
df[["StationId", "Datetime"]].head(20)

C:\Users\Yosua Triantara\AppData\Local\Temp\ipykernel_28944\3288464925.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH)

   StationId             Datetime
0      AP001  2017-11-24 17:00:00
1      AP001  2017-11-24 18:00:00
2      AP001  2017-11-24 19:00:00
3      AP001  2017-11-24 20:00:00
4      AP001  2017-11-24 21:00:00
5      AP001  2017-11-24 22:00:00
6      AP001  2017-11-24 23:00:00
7      AP001  2017-11-25 00:00:00
8      AP001  2017-11-25 01:00:00
9      AP001  2017-11-25 02:00:00
10     AP001  2017-11-25 03:00:00
11     AP001  2017-11-25 04:00:00
12     AP001  2017-11-25 05:00:00
13     AP001  2017-11-25 06:00:00
14     AP001  2017-11-25 07:00:00
15     AP001  2017-11-25 08:00:00
16     AP001  2017-11-25 09:00:00
17     AP001  2017-11-25 10:00:00
18     AP001  2017-11-25 11:00:00
19     AP001  2017-11-25 12:00:00

In [9]:
df["Datetime"].dtype

dtype('O')

In [10]:
df["Datetime"] = pd.to_datetime(
    df["Datetime"],
    errors="raise"
)

print(df["Datetime"].dtype)

datetime64[ns]

In [11]:
print("Jumlah nilai kosong setelah parsing:")

print(df["Datetime"].isna().sum())

Jumlah nilai kosong setelah parsing:
0

In [12]:
df = df.sort_values(
    by=["StationId", "Datetime"]
).reset_index(drop=True)

In [13]:
df[["StationId", "Datetime"]].head(20)

   StationId            Datetime
0      AP001 2017-11-24 17:00:00
1      AP001 2017-11-24 18:00:00
2      AP001 2017-11-24 19:00:00
3      AP001 2017-11-24 20:00:00
4      AP001 2017-11-24 21:00:00
5      AP001 2017-11-24 22:00:00
6      AP001 2017-11-24 23:00:00
7      AP001 2017-11-25 00:00:00
8      AP001 2017-11-25 01:00:00
9      AP001 2017-11-25 02:00:00
10     AP001 2017-11-25 03:00:00
11     AP001 2017-11-25 04:00:00
12     AP001 2017-11-25 05:00:00
13     AP001 2017-11-25 06:00:00
14     AP001 2017-11-25 07:00:00
15     AP001 2017-11-25 08:00:00
16     AP001 2017-11-25 09:00:00
17     AP001 2017-11-25 10:00:00
18     AP001 2017-11-25 11:00:00
19     AP001 2017-11-25 12:00:00

In [14]:
is_sorted = (
    df
    .sort_values(["StationId", "Datetime"])
    .equals(df)
)

print(f"Data sudah terurut : {is_sorted}")

Data sudah terurut : True

In [16]:
OUTPUT_PATH = "../data/processed/station_hour_sorted.csv"
os.makedirs("../data/processed", exist_ok=True)

df.to_csv(
    OUTPUT_PATH,
    index=False
)

print(f"Dataset berhasil disimpan di:\n{OUTPUT_PATH}")

Dataset berhasil disimpan di:
../data/processed/station_hour_sorted.csv